# Docker Compose for Sedna Web Crawler

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sedna-backend
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - KTOR_ENV=production
    networks:
      - sedna-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sedna-frontend
    user: root
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sedna-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  sedna-network:
    driver: bridge
    name: sedna-network
