# Development Docker Compose for Sedna Web Crawler
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: build  # Stop at build stage for development
    container_name: sedna-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/.gradle  # Exclude gradle cache from volume mount
    environment:
      - JAVA_OPTS=-Xmx512m
      - KTOR_ENV=development
    networks:
      - sedna-network
    command: ["./gradlew", "run", "--continuous"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: build  # Stop at build stage for development
    container_name: sedna-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from volume mount
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
    networks:
      - sedna-network
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - backend
    restart: unless-stopped

networks:
  sedna-network:
    driver: bridge
    name: sedna-network-dev
